### ISSUE TITLE
[FEAT]:  check if _async methods should be blueprint native

### ISSUE THREAD

**Issue by dorotaphanSiili** [apigear-io/template-unreal#44]
### Description

does it make sense to implement asynchronous versions in blueprints - will it be truly async (blueprint classes can't be called in other than main thread)?
If not make it only blueprint callable and implemente in cpp only

**Comment by w4bremer** [comment]
Sounds reasonable but is not possible due consistency. If the interface is `Blueprintable` all functions must also be `BlueprintImplementableEvent`.

If you try to remove that, you get the following error message in UE 4.27
`LogCompile: Error: Blueprint implementable interfaces cannot contain BlueprintCallable functions that are not BlueprintImplementableEvents.  Use CannotImplementInterfaceInBlueprint on the interface if you wish to keep this function.`

Wondering whether there is a better way to achieve this, but cannot think of one at the moment.
